version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: ../infra/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backend/models:/app/models
    depends_on:
      - redis
    networks:
      - climatech-network

  frontend:
    build:
      context: ./client
      dockerfile: ../infra/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - NODE_ENV=production
    networks:
      - climatech-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - climatech-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - climatech-network

volumes:
  redis_data:

networks:
  climatech-network:
    driver: bridge