apiVersion: apps/v1
kind: Deployment
metadata:
  name: climatech-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: climatech-backend
  template:
    metadata:
      labels:
        app: climatech-backend
    spec:
      containers:
      - name: backend
        image: ${AZURE_CONTAINER_REGISTRY}/climatech-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: BACKEND_HOST
          value: "0.0.0.0"
        - name: BACKEND_PORT
          value: "8000"
        - name: FRONTEND_URL
          value: "${FRONTEND_URL}"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: climatech-backend-service
spec:
  selector:
    app: climatech-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: climatech-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: climatech-frontend
  template:
    metadata:
      labels:
        app: climatech-frontend
    spec:
      containers:
      - name: frontend
        image: ${AZURE_CONTAINER_REGISTRY}/climatech-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "${BACKEND_URL}"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: climatech-frontend-service
spec:
  selector:
    app: climatech-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer